= Changelog

== Version 0.8.1
[cols="1,2,<10a", options="header"]
|===
|ID|Type|Description
|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/20[#20]
|Fix
|Configuration tool now supports API Gateway 7.5.3

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/21[#21]
|Fix
|Support verbose mode of configuration tool for goal `apigw:deploy`.

|===

== Version 0.8.0
[cols="1,2,<10a", options="header"]
|===
|ID|Type|Description
|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/11[#11]
|Enhancement
|Deployment to gateway via plugin.

The plugin now supports to deploy a project directly via the plugin goal `apigw:deploy`. Only the standard deployment is supported. The deployment of static files and JARs are not supported.

New properties:

  * `axway.anm.host`: Host of the Admin Node Manager.
  * `axway.anm.port`: Port of the Admin Node Manager (default: 8090).
  * `axway.anm.user`: User to connect to the Admin Node Manager (default: admin).
  * `axway.anm.password`: Password of the user.
  * `axway.deploy.group`: Name of the group the project is deployed to.
  * `axway.passphrase.pol`: Passphrase for `.pol` and `.env` packages.
  * `axway.passphrase.fed`: Passphrase for `.fed` packages.
  * `axway.passphrase.deploy`: Passphrase for deployment group.
  * `axway.config.envs`: Path to environmentalized fields configuration file.
  * `axway.config.certs`: Path to certificates configuration file.
  * `axway.config.props`: Path to properties configuration file.

Deleted properties:

  * `axway.passphrase.in`: replaced by `axway.passphrase.pol`
  * `axway.passphrase.out`: replaced by `axway.passphrase.out`
  * `propertyFile`: replaced by `axway.config.props`
  * `certsFile`: replaced by `axway.config.certs`

|===

== Version 0.7.0

[cols="1,2,<10a", options="header"]
|===
|ID|Type|Description
|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/17[#17]
|Enhancement
|Check expiration of configured certificates.

The plugin and the configuration tool now supports to check if configured certificates expires within a given number of days.
If at least one certificate expires within the time frame an error will be raised.

For the configuration tool the check is disabled by default.

For the plugin the default number of days is 10.
To disable the check for the plugin specify set `axway.tools.cfg.cert.expirationDays` property to -1.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/18[#18]
|Enhancement
|Don't create "info" section for "update" certificates.
Information about the configured certificates are written to log instead.

Previously the configuration tool has written the "info" section (see below).
This will change a source file, which is not suitable for build environments.

.previous-cert-config.json
....
            "update": {
                "file": "cert/server.p12", 
                "info": { <1>
                    "not_after": "2020-05-21T07:02:00+02:00", 
                    "subject": "CN=server, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }, 
                "password": "server",
                "type": "p12"
            }
....
<1> Information about the configured certificate, will no longer be created or updated.

The "info" section is no longer created or updated for "update" certificates.

.cert-config.json
....
            "update": {
                "file": "cert/server.p12", 
                "password": "server",
                "type": "p12"
            }
....


NOTE: To enable the previous behavior, use the `--cert-config-update` parameter of the configuration tool or the `axway.tools.cfg.cert.updateConfigured` property of the plugin.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/19[#19]
|Fix
|On flattening the resulting POM a NullPointerException occurred if the `pom.xml` has no <build> element (e.g. in case of the <build> element is defined in the parent POM).

The issue occurred for server and deployment projects.
|===

== Version 0.6.0

[cols="1,2,<10a", options="header"]
|===
|ID|Type|Description
|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/15[#15]
|Enhancement
|Optionally skip `package` goal.

For CI/CD pipelines it would be usefully to separate the package and deployment phase.
A property `axway.skipPackaging` is provided to skip the `package` goal in case of the target archive already exists.

NOTE: There is no check if source files are newer than the target archive.
So ensure that the package goal was executed before.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/16[#16]
|Enhancement
|Support simulation mode for configuration tool.

In simulation mode no output files (`.fed` or `.env`) are written.
Also non existing certificate files will be ignored.

To ensure proper configuration files, unconfigured fields or certificates will still raise a build error.

NOTE: The `buildtemplate` tool is removed as it can be fully replaced by the `buildfed` tool.
|===

== Version 0.5.0

[cols="1,2,<10a", options="header"]
|===
|ID|Type|Description

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/1[#1]
|Enhancement
|Configuration tool now supports passphrases for input archives (.pol and .env) and for output archives (.fed and .env).

Example:

  buildfed -e gateway.env -p gateway.pol -c gateway.config.json -passphrase-in=foo -passphrase-out=bar --output-fed=gateway.fed

Uses the passphrase "foo" to open the `gateway.env` and `gateway.pol` archive and uses the passphrase "bar" to write the configured `gateway.fed` file.

Limitation:

 * For all input archives, the same passphrase will be used.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/2[#2]
|Enhancement
|The source directory layout for the configuration tool is changed.
The tool can be invoked directly from the cloned project folder, now.

Example:

_Windows_

  > git clone https://github.com/Axway-API-Management-Plus/apigw-maven-plugin.git
  > cd apigw-mavem-plugin
  > set AXWAY_HOME=c:\axway
  > src\main\resources\scripts\buildfed.cmd -h

_Unix_

  $ git clone https://github.com/Axway-API-Management-Plus/apigw-maven-plugin.git
  $ cd apigw-mavem-plugin
  $ export AXWAY_HOME=/opt/axway
  $ src/main/resources/scripts/buildfed.sh -h

Extracting the tool from the Maven plugin via the `apigw:tools` goal is still supported.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/7[#7]
|Fix
|Configured certificates were not updated by configuration tool.

Now updating or adding certificates works as expected.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/6[#6]
|Enhancement
|Example for using standalone configuration tool added.

Folder: `example/config-tool`

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/8[#8]
|Enhancement
|Working directories of PolicyStudio consolidated under a single `.studio` folder.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/3[#3]
|Enhancement
|Generate default `.gitignore` file on initialization.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/4[#4]
|Enhancement
|Maven plugin now supports passphrases for reading input packages and for writing output packages.
Applicable for server and deployment packages only.

You can use the properties `axway.passphrase.in` and `axway.passphrase.out` to specify the passphrases for reading and writing packages.

_Examples:_

  ~/server-project$ mvn -Daxway.passphrase.out=changeme clean install

Generates a server archive containing passphrase protected `.pol` and `.env` packages.

  ~/deploy-project$ mvn -Daxway.passphrase.in=changeme -Daxway.passphrase.out=changed clean install

Uses a passphrase protected server archive and generates a deployment archive containing a passphrase protected `.fed` package.
|===
