= Changelog

== Version 0.5.0

=== Enhancements

[cols="1,2,<10a", options="header"]
|===
|ID|Type|Description

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/1[#1]
|Enhancement
|Configuration tool now supports passphrases for input archives (.pol and .env) and for output archives (.fed and .env).

Example:

  buildfed -e gateway.env -p gateway.pol -c gateway.config.json -passphrase-in=foo -passphrase-out=bar --output-fed=gateway.fed

Uses the passphrase "foo" to open the `gateway.env` and `gateway.pol` archive and uses the passphrase "bar" to write the configured `gateway.fed` file.

Limitation:

 * For all input archives, the same passphrase will be used.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/2[#2]
|Enhancement
|The source directory layout for the configuration tool is changed.
The tool can be invoked directly from the cloned project folder, now.

Example:

_Windows_

  > git clone https://github.com/Axway-API-Management-Plus/apigw-maven-plugin.git
  > cd apigw-mavem-plugin
  > set AXWAY_HOME=c:\axway
  > src\main\resources\scripts\buildfed.cmd -h

_Unix_

  $ git clone https://github.com/Axway-API-Management-Plus/apigw-maven-plugin.git
  $ cd apigw-mavem-plugin
  $ export AXWAY_HOME=/opt/axway
  $ src/main/resources/scripts/buildfed.sh -h

Extracting the tool from the Maven plugin via the `apigw:tools` goal is still supported.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/7[#7]
|Fix
|Configured certificates were not updated by configuration tool.

Now updating or adding certificates works as expected.

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/6[#6]
|Enhancement
|Example for using standalone configuration tool added.

Folder: `example/config-tool`

|https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/issues/8[#8]
|Enhancement
|Working directories of PolicyStudio consolidated under a single `.studio` folder.
|===
