= Configuration Tool

For the configuration of the `.fed` and `.env` files the Maven plugin uses Python scripts.
The scripts can also be used as an independent tool.
There are two tools available.

== Build FED

The FED builder takes the `.pol` and `.env` archive and a JSON configuration file to configure the environmentalized fields of the project.
The script is invoked with the `jython` interpreter provided with the development and deployment tools of the API Gateway.

....
$ jython buildfed.py --help
Usage: buildfed.py OPTIONS

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -v, --verbose         Enable verbose messages [optional]
  -e FILEPATH, --env=FILEPATH
                        Path of environment archive (.env)
  -p FILEPATH, --pol=FILEPATH
                        Path of policy archive (.pol)
  -c FILEPATH, --config=FILEPATH
                        Path of JSON configuration file
  --prop=FILEPATH       Path of JSON property file [optional]
  --cert=FILEPATH       Path of JSON certificate configuration file [optional]
  --output-fed=FILEPATH
                        Path of output deployment archive file (.fed) [optional]
  --output-env=FILEPATH
                        Path of output environment archive file (.env) [optional]
....

If environmentalized fields are not configured, the build fails.
Missing fields are automatically added to the configuration file.

[cols="1,5", options="header"]
|===
|Option
|Description


|--env
|The `.env` file as generated by the `projpack` tool.
The option is mandatory.

|--pol
|The `.pol` file as generated by the `projpack` tool.
The option is mandatory.

|--config
|The JSON configuration file for environmentalized fields.
The option is mandatory.

|--prop
|An optional JSON file containing the property configuration.

|--cert
|An optional JSON file containing the certificate configuration.

|--output-fed
|The path of the configured `.fed` file.
If missing, no `.fed` file is generated.

|--output-env
|The path of the configured `.env` file.
If missing, no `.env` file is generated. 
|===

TIP: If no output file is specified the tool can be used to check the configuration and to update the configuration files.

== Build Template

....
$ jython buildtemplate.py --help
Usage: buildtemplate.py OPTIONS

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -v, --verbose         Enable verbose messages [optional]
  -e FILEPATH, --env=FILEPATH
                        Path of environment archive (.env)
  -p FILEPATH, --pol=FILEPATH
                        Path of policy archive (.pol)
  -c FILEPATH, --config=FILEPATH
                        Path of JSON configuration file
  --cert=FILEPATH       Path of JSON file for used certificates [optional]
....

