= Configuration Tool
:Author: Martin Look
:Email: mlook@axway.com
:source-highlighter: prettify
ifdef::env-github[]
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

For the configuration of the `.fed` and `.env` files the Maven plugin uses Python scripts.
The scripts can also be used as an independent tool.
There are two tools available.

== Build FED

The FED builder takes the `.pol` and `.env` archive and JSON files to configure the environmentalized fields and certificates of the project.
The script is invoked with the `jython` interpreter provided with the package and deployment tools of the API Gateway.

....
$ jython buildfed.py --help
Usage: buildfed.py OPTIONS

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -v, --verbose         Enable verbose messages [optional]
  -e FILEPATH, --env=FILEPATH
                        Path of environment archive (.env)
  -p FILEPATH, --pol=FILEPATH
                        Path of policy archive (.pol)
  -c FILEPATH, --config=FILEPATH
                        Path of JSON configuration file
  --prop=FILEPATH       Path of JSON property file [optional]
  --cert=FILEPATH       Path of JSON certificate configuration file [optional]
  --output-fed=FILEPATH
                        Path of output deployment archive file (.fed) [optional]
  --output-env=FILEPATH
                        Path of output environment archive file (.env) [optional]
  -D NAME:VALUE, --define=NAME:VALUE
                        Define a system property [multiple]
....

If environmentalized fields or certificates are not configured, the build fails.
Missing fields or certificates are automatically added to the configuration file.

[cols="1,5", options="header"]
|===
|Option
|Description


|--env
|The `.env` file as generated by the `projpack` tool.
The option is mandatory.

|--pol
|The `.pol` file as generated by the `projpack` tool.
The option is mandatory.

|--config
|The JSON configuration file for environmentalized fields.
The option is mandatory.

|--prop
|An optional JSON file containing the property configuration.

|--cert
|An optional JSON file containing the certificate configuration.

|--output-fed
|The path of the configured `.fed` file.
If missing, no `.fed` file is generated.

|--output-env
|The path of the configured `.env` file.
If missing, no `.env` file is generated. 

|--define
|Define a system property `name:value`.
System properties can be used instead of custom defined properties.
|===

TIP: If no output file is specified the tool can be used to check the configuration and to update the configuration files.

Additionally to the properties within the property or configuration file, the plugin provides a set of predefined system properties.
[cols="1,5,2", options="header"]
.Predefined System Properties
|===
|System Property
|Description
|Provided by

|_system.artifact.group
|Group of the project artifact.
|Plugin

|_system.artifact.name
|Name of the project artifact.
|Plugin

|_system.artifact.ver
|Version of the project artifact.
|Plugin

|_system.artifact.id
|Complete ID of the project artifact.
|Plugin

|_system.build.datetime
|Build date and time in ISO format (YYYY-MM-DD'T'HH:MM:SS.S)
|Config Tool
|===

== Build Template

The template builder tool is used to build templates for the configuration files.

....
$ jython buildtemplate.py --help
Usage: buildtemplate.py OPTIONS

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -v, --verbose         Enable verbose messages [optional]
  -e FILEPATH, --env=FILEPATH
                        Path of environment archive (.env)
  -p FILEPATH, --pol=FILEPATH
                        Path of policy archive (.pol)
  -c FILEPATH, --config=FILEPATH
                        Path of JSON configuration file
  --cert=FILEPATH       Path of JSON file for used certificates [optional]
....

== Configuration Files

For the configuration of the environment specific deployment archive, various configuration files are used.
All configuration files are JSON documents.
The schema of the JSON is not validated, so any arbitrary property can be added.
Properties not known by the plugin will be ignored.

If a configuration file is updated by the plugin, all properties, including custom properties, are written.

TIP: When a configuration file is written by the plugin, all JSON properties are sorted.
This makes diff & merge easy.

=== Environmentalized Fields

For configuring environmentalized fields a JSON file having an `entities` property is used.
For each configured environmentalized entity a property exists.
The name of the property is the _short hand key_ of the entity.

.src/main/gateway.config.json
[source,json]
----
{
    "entities": { <1>
        "/[CircuitContainer]name=Hello World/[FilterCircuit]name=Hello World Message/[SetAttributeFilter]name=Set name": { <2>
            "description": "Name for the 'Hello World' message.", 
            "fields": {
                "attributeValue#0": { <3>
                    "property": null, <4>
                    "type": "string", <5> 
                    "used": true, <6>
                    "value": null <7>
                }
            }
        },
        "/[CircuitContainer]name=Hello World/[FilterCircuit]name=Hello World Message/[SetAttributeFilter]name=Build time": {
            "description": "Build time in ISO format.", 
            "fields": {
                "attributeValue#0": {
                    "property": "_system.build.datetime", <8>
                    "type": "string",
                    "used": true,
                    "value": null
                }
            }
        }
    }
}
----
<1> Environmentalized entities are configured under an `entities` attribute.
<2> Short hand key of the environmentalized entity.
<3> Name and index of the environmentalized field.
<4> Name of the property containing the value (see property file).
_null_ or missing property indicates that no property is used to configure the value. 
<5> Type of the field (just for documentation, don't change it).
<6> Indicates if the configured field is used.
If _false_ the field is no longer environmentalized or the entity is renamed or removed.
The property is automatically maintained by the plugin. 
<7> Value of the field.
_null_ indicates an unconfigured field.
If `value` and `property` are configured the `property` value has precedence.
<8> Use value of the predefined system property `_system.build.datetime`.

=== Certificates

[source,json]
----
{
    "certificates": { <1>
        "extern-crt": { <2>
            "origin": { <3>
                "info": {
                    "not_after": "2020-05-21T07:04:00+02:00", <4>
                    "subject": "CN=extern, O=Axway, L=Berlin, ST=Berlin, C=DE" <5>
                }
            },
            "update": { <6>
                "file": "cert/extern.crt", <7>
                "info": { <8>
                    "not_after": "2020-05-21T07:04:00+02:00", 
                    "subject": "CN=extern, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }, 
                "type": "crt" <9>
            }
        }, 
        "server-p12": {
            "origin": {
                "info": {
                    "not_after": "2020-05-21T07:02:00+02:00", 
                    "subject": "CN=server, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }
            },
            "update": {
                "file": "cert/server.p12", 
                "info": {
                    "not_after": "2020-05-21T07:02:00+02:00", 
                    "subject": "CN=server, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }, 
                "password": "server", <10>
                "type": "p12"
            }
        }, 
        "test": {
            "origin": {
                "info": {
                    "not_after": "2021-09-30T16:01:15+02:00", 
                    "subject": "CN=DST Root CA X3, O=Digital Signature Trust Co."
                }
            },
            "update": null <11>
        },
        "test2": { <12>
            "update": {
                "file": "cert/server.p12", 
                "info": {
                    "not_after": "2020-05-21T07:02:00+02:00", 
                    "subject": "CN=server, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }, 
                "password-property": "server.password", <13> 
                "type": "p12"
            }
        }
    }
}
----
<1> Certificates are configured under a `certificates` attribute.
<2> Unique alias for storing the certificate in the certificate store.
<3> Information of the origin certificate.
A missing `origin` attribute indicates the origin certificate store doesn't has a certificate with this alias.
<4> Expiration date of the origin certificate.
<5> Subject of the origin certificate.
<6> Defines the certificate to update the certificate with the same alias within the certificate store.
A missing `update` attribute indicates a new/unconfigured certificate.
<7> Path to the new certificate file.
<8> Information of the new certificate.
Will be updated automatically be the plugin.
<9> Type of the certificate.
`crt` for certificates and `p12` for certificates with key.
<10> Password to for the `.p12` file.
<11> _null_ value indicates that the certificate will not be updated.
<12> Certificate without a `origin` attribute.
This certificate will be added to the certificate store.
<13> Password for the `.p12` file is retrieved from the property configuration file.

=== Properties

[source,json]
----
{
    "properties": { <1>
        "name1": "value1", <2>
        "name2": "value2"
    }
}
----
<1> Properties are configured under a `properties` attribute.
<2> For each configured property a name/value pair has to exist.
The property is identified by its _name_.
