= Reference
ifdef::env-github[]
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

== Project Types

This section describes the various projects types.
The described directory layout is the default structure as assumed by the plugin.

=== Policy Project
Policy project contain shared and reusable policies.
No sever settings are included in the project.
Policy projects may depend on other policy projects or external libraries (JARs).

==== Directory Layout

[listing, subs="verbatim,macros"]
----
icon:folder-o[] project-home
  icon:file-text-o[] pom.xml <1>
  icon:folder-o[] src
    icon:folder-o[] main <2>
      icon:folder-o[] axwgw
        icon:folder-o[] policies <3>
          icon:file-text-o[] config.xml
          icon:file-text-o[] ...
        icon:folder-o[] resources
          icon:folder-o[] staticFiles <4>
    icon:folder-o[] test <5> 
      icon:folder-o[] policies <6>
        icon:file-text-o[] config.xml
        icon:file-text-o[] ...
----
<1> Maven Project Object Model, which describes your project and the dependencies
<2> Main sources of your project
<3> Policies as to be opened by PolicyStudio
<4> Folder for static files (e.g. HTML, text, JavaScript, ...)
<5> Test sources for your project
<6> Server project for testing your project

==== Archive Content
The outcome of the policy project is the policy archive artifact.
It contains the policies of the project (as edited in PolicyStudio) and the static files.

[listing, subs="verbatim,macros"]
----
icon:file-zip-o[] policy-archive.axpar <1>
  icon:folder-o[] policies <2>
    icon:file-text-o[] config.xml
    icon:file-text-o[] ...
  icon:folder-o[] staticFiles <3>
----
<1> Generated policy archive.
<2> Policies of the project (copied from `src/main/axwgw/policies`).
<3> Static files belonging to the project (copied from `src/main/resources/staticFiles`).
The static files are optional.

=== Server Project
Server projects represent gateway instances.
They contain policies and server settings.
Server projects may depend on other policy projects or external libraries (JARs).
Server projects are environment independent.

==== Directory Layout

[listing, subs="verbatim,macros"]
----
icon:folder-o[] project-home
  icon:file-text-o[] pom.xml <1>
  icon:folder-o[] src
    icon:folder-o[] main <2>
      icon:folder-o[] axwgw
        icon:folder-o[] policies <3>
          icon:file-text-o[] config.xml
          icon:file-text-o[] ...
        icon:folder-o[] resources
          icon:folder-o[] staticFiles <4>
----
<1> Maven Project Object Model, which describes your project and the dependencies
<2> Main sources of your project
<3> Policies, including server setting, as to be opened by PolicyStudio
<4> Folder for static files (e.g. HTML, text, JavaScript, ...)

==== Archive Content
The outcome of a server project is a server archive artifact.
The server archive contains everything required for a deployment of a gateway instance, except the environment dependent configuration.

[listing, subs="verbatim,macros"]
----
icon:file-zip-o[] server-archive.axsar <1>
  icon:folder-o[] lib <2>
  icon:folder-o[] staticFiles <3>
  icon:file-o[] gateway.pol <4>
  icon:file-o[] gateway.env <5>
  icon:file-o[] readme-server-archive.txt <6>
----
<1> Generated server archive.
<2> Folder containing dependent JARs.
<3> Static files belonging to the gateway instance.
The files are copied from the `staticFiles` folders of all dependent policy archives.
<4> Packed `.pol` archive containing the server configuration and polices (including policies of all dependent policy archives)
<5> `.env` file containing all environment specific information.
The environment is not configured and should be treated as environment independent.
<6> Generated readme file describing the content of the archive (e.g. version of dependent policy archives)

=== Deployment Project
Deployment projects are used to configure API gateways for specific environments or groups based on an environment independent server project.
A deployment project depends on exactly one server project.

==== Directory Layout
[listing, subs="verbatim,macros"]
----
icon:folder-o[] project-home
  icon:file-text-o[] pom.xml <1>
  icon:folder-o[] src
    icon:folder-o[] main <2>
      icon:folder-o[] axwgw
        icon:file-text-o[] gateway.config.json <3>
----
<1> Maven Project Object Model, which describes your project and the dependencies
<2> Main sources of your project
<3> Configuration file as to be used by the configuration tool.

==== Archive Content
The outcome of a deployment project is a environment specific deployment archive.
It contains a fully configured API gateway instance including required static files and depending JARs.

[listing, subs="verbatim,macros"]
----
icon:file-zip-o[] deploy-archive.axdar <1>
  icon:folder-o[] lib <2>
  icon:folder-o[] staticFiles <3>
  icon:file-o[] gateway.fed <4>
  icon:file-o[] gateway.pol <5>
  icon:file-o[] gateway.env <6>
  icon:file-o[] readme-deployment-archive.txt <7>
  icon:file-o[] readme-server-archive.txt <8>
----
<1> Generated server archive.
<2> Folder containing dependent JARs.
<3> Static files belonging to the gateway instance.
The files are copied from the `staticFiles` folders of all dependent policy archives.
<4> Configured `.fed` file.
It is environment specific and contains all configured certificates and environmentalized fields.
<5> Packed `.pol` archive containing the server configuration and polices (including policies of all dependent policy archives)
<5> Configured `.env` file containing all environment specific information.
All certificates and environmentalized fields are replace by configured values.
<6> Generated readme file describing the content of the archive (e.g. version of depnednt server archive).
<7> Generated readme file describing the content of the archive (e.g. version of dependent policy archives).
Copied from server archive.

== Properties

The plugin can be configured by various properties.
For most properties a default value exists, so the configuration effort is reduced to a minimum.

.Properties
[cols="1,3", options="header"]
|===
|Property|Description

|axway.home
|Home directory of the installed Axway API Gateway suite.
This property has to be defined before using the plugin.

Default: _none_

|axway.home.apigw
|Home directory of the installed AI Gateway.

Default: ${axway.home}/apigateway

|axway.home.policystudio
|Home directory of installed PolicyStudio.

Default: ${axway.home}/policystudio

|axway.dir.source
|Directory of gateway or configuration file source code used by the plugin.
${basedir}/src/main/axwgw

|axway.dir.resources
|Directory of resources.

Default: ${basedir}/src/main/resources

|axway.dir.sharedProjects
|Directory to extracted dependent policy projects.

Default: ${project.build.directory}/sharedProjects

|axway.dir.testServer
|Source directory for the test API Gateway (only for policy projects).

Default: ${basedir}/src/test/policies

|axway.policystudio.data
|Data directory for project specific PolicyStudio data.

Default: ${basedir}/.data

|axway.policystudio.dir
|Data directory for project specific PolicyStudio configuration.

Default: ${basedir}/.policystudio

|axway.dir.archive.build
|Directory for building project archives.

Default: ${project.build.directory}/axway-archive

|axway.template.gateway.fed
|Template for the server project.

Default: ${axway.home}/apigateway/system/conf/templates/BlankConfiguration-VordelGateway.fed

|axway.template.policies.fed
|Template for the policy project.

Default: ${axway.home}/apigateway/system/conf/templates/BlankNoSettingsConfiguration-VordelGateway.fed

|axway.tools.cfg.verbose
|Set to _true_ to enable verbose mode for internal configuration tool.

Default: false
|===
