= Reference

== Configuration Files

For the configuration of the environment specific deployment archive, various configuration files are used.
All configuration files are JSON documents.
The schema of the JSON is not validated, so any arbitrary property can be added.
Properties not known by the plugin will be ignored.

If a configuration file is updated by the plugin all attribute, including the custom attributes, are written.

TIP: When a configuration file is written by the plugin, all JSON properties are sorted.
This makes diff & merge easy.

=== Environmentalized Fields

.src/main/gateway.config.json
[source,json]
----
{
    "entities": { <1>
        "/[CircuitContainer]name=Hello World/[FilterCircuit]name=Hello World Message/[SetAttributeFilter]name=Set name": { <2>
            "description": "", 
            "fields": {
                "attributeValue#0": { <3>
                    "property": null <4>
                    "type": "string", <5> 
                    "used": true, <6>
                    "value": null <7>
                }
            }
        }
    }
}
----
<1> Environmentalized entities are configured under an `entities` attribute.
<2> Short handed key of the environmentalized entity.
<3> Name and index of the environmentalized field.
<4> Name of the property containing the value (see property file).
_null_ or missing property indicates that no property is used to configure the value. 
<5> Type of the field (just for documentation, don't change it).
<6> Indicates if the configured field is used.
If _false_ the field is no longer environmentalized or the entity is renamed or removed.
The property is automatically maintained by the plugin. 
<7> Value of the field.
_null_ indicates an unconfigured field.
If `value` and `property` are configured the `property` value has precedence.


=== Certificates

[source,json]
----
{
    "certificates": { <1>
        "extern-crt": { <2>
            "origin": { <3>
                "info": {
                    "not_after": "2020-05-21T07:04:00+02:00", <4>
                    "subject": "CN=extern, O=Axway, L=Berlin, ST=Berlin, C=DE" <5>
            },
            "update": { <6>
                "file": "c:/temp/cert/extern.crt", <7>
                "info": { <8>
                    "not_after": "2020-05-21T07:04:00+02:00", 
                    "subject": "CN=extern, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }, 
                "type": "crt" <9>
            }
        }, 
        "server-p12": {
            "origin": {
                "info": {
                    "not_after": "2020-05-21T07:02:00+02:00", 
                    "subject": "CN=server, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }
            },
            "update": {
                "file": "c:/temp/cert/server.p12", 
                "info": {
                    "not_after": "2020-05-21T07:02:00+02:00", 
                    "subject": "CN=server, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }, 
                "password": "server", <10>
                "type": "p12"
            }
        }, 
        "test": {
            "origin": {
                "info": {
                    "not_after": "2021-09-30T16:01:15+02:00", 
                    "subject": "CN=DST Root CA X3, O=Digital Signature Trust Co."
            },
            "update": null <11>
        },
        "test2": { <12>
            "update": {
                "file": "c:/temp/cert/server.p12", 
                "info": {
                    "not_after": "2020-05-21T07:02:00+02:00", 
                    "subject": "CN=server, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }, 
                "password-property": "server.password", <13> 
                "type": "p12"
            }
        }
    }
}
----
<1> Certificates are configured under a `certificates` attribute.
<2> Unique alias for storing the certificate in the certificate store.
<3> Information of the origin certificate.
A missing `origin` attribute indicates the origin certificate store doesn't has a certificate with this alias.
<4> Expiration date of the origin certificate.
<5> Subject of the origin certificate.
<6> Defines the certificate to update the certificate with the same alias within the certificate store.
A missing `update` attribute indicates a new/unconfigured certificate.
<7> Path to the new certificate file.
<8> Information of the new certificate.
Will be updated automatically be the plugin.
<9> Type of the certificate.
`crt` for certificates and `p12` for certificates with key.
<10> Password to for the `.p12` file.
<11> _null_ value indicates that the certificate will not be updated.
<12> Certificate without a `origin` attribute.
This certificate will be added to the certificate store.
<13> Password for the `.p12` file is retrieved from the property configuration file.

=== Properties

[source,json]
----
{
    "properties": { <1>
        "name1": "value1", <2>
        "name2": "value2"
    }
}
----
<1> Properties are configured under a `properties` attribute.
<2> For each configured property a name/value pair has to exist.
The property is identified by its _name_.
